sonar.projectKey=rdx-sip-bs-ms
sonar.sources=src/config,src/controllers,src/dao,src/dbConnect,src/interfaces,src/models,src/utils 
sonar.exclusions=**/*.test.js, **/kafka/*.ts, **/*.spec.ts, **/*.yaml, **/adapters/*.ts, **/utils/logger/*.ts, src/controllers/_test_, **/_test_/**, helm-chart-deployment/**/*
sonar.language=ts
sonar.sourceEncoding=UTF-8
sonar.clover.reportPaths=coverage/clover.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.tests=tests

sonar.host.url=https://sonarqube.kenvue.com/tutorials?id=rdx-sip-bs-ms
