export const projectMapping = (auditData) => ({
  productSipId: auditData?.productSipId,
  productName: auditData?.productName,
  brandName: auditData?.brandName,
  projectId: auditData?.projectId,
  projectName: auditData?.projectName,
  description: auditData?.description,
  shortBrandCode: auditData?.shortBrandCode,
  isDeleted: auditData?.isDeleted,
  users: auditData?.users?.map((element) => ({
    name: element?.name || "",
    role: element?.role || "",
    mail: element?.mail || "",
  })),
});

export const assessmentBaseLineMapping = (auditData) => ({
  assessmentId: auditData?.assessmentId,
  name: auditData?.name,
  isFormulationDataCompleted: auditData?.isFormulationDataCompleted,
  isPackagingDataCompleted: auditData?.isPackagingDataCompleted,
  isFormulationCalculated: auditData?.isFormulationCalculated,
  isFormulationEOLCalculated: auditData?.isFormulationEOLCalculated,
  isPackagingCalculated: auditData?.isPackagingCalculated,
  isSpiceCalculated: auditData?.isSpiceCalculated,
  isGreenChemistryCalculated: auditData?.isGreenChemistryCalculated,
  isSustainabilityPackagingCalculated:
    auditData?.isSustainabilityPackagingCalculated,
  isLCACalculated: auditData?.isLCACalculated,
  isGreenChemistryRollupCalculated: auditData?.isGreenChemistryRollupCalculated,
  isSustainabilityPackagingRollupCalculated:
    auditData?.isSustainabilityPackagingRollupCalculated,
  isCalculatedButtonClicked: auditData?.isCalculatedButtonClicked,
  isBaselineCalcUpdated: auditData?.isBaselineCalcUpdated,
  isBaselineSkipped: auditData?.isBaselineSkipped,
  justification: auditData?.justification,
  isLPP: auditData?.isLPP,
  fg_spec: auditData?.fg_spec,
  formula_number: auditData?.formula_number,
  lab_notebook_code: auditData?.lab_notebook_code,
  pc_spec: auditData?.pc_spec,
  sku_erp_code: auditData?.sku_erp_code,
  zone: auditData?.zone,
  net_content: auditData?.net_content,
  formulation: {
    fmlCode: auditData?.formulation?.fmlCode,
    description: auditData?.formulation?.description,
    netContent: auditData?.formulation?.netContent,
    netContentUnit: auditData?.formulation?.netContentUnit,
    productionZone: auditData?.formulation?.productionZone,
    salesZone: auditData?.formulation?.salesZone,
    productSegment: auditData?.formulation?.productSegment,
    productSubSegment: auditData?.formulation?.productSubSegment,
    useDose: auditData?.formulation?.useDose,
    useDoseUnit: auditData?.formulation?.useDoseUnit,
    useScenario: auditData?.formulation?.useScenario,
    consumablesUsed: auditData?.formulation?.consumablesUsed,
    isEdited: auditData?.formulation?.isEdited,
    isCalculating: auditData?.formulation?.isCalculating,
    isCalculated: auditData?.formulation?.isCalculated,
    rawMaterials: auditData?.formulation?.rawMaterials?.map((element) => ({
      tradeName: element?.tradeName || "",
      rawMaterialId: element?.rawMaterialId || "",
      percentage: element?.percentage || "",
    })),
  },
  packaging_level: auditData?.packaging_level?.map((element) => ({
    packaging_level: element?.packaging_level || "",
    isrecyclable: element?.isrecyclable || "",
    recyclability_status: element?.recyclability_status || "",
    productEvaluation: element?.productEvaluation || "",
    isManualEdit: element?.isManualEdit || "",
    components: element.components?.map((componentElement) => ({
      pc_nm: componentElement?.pc_nm || "",
      description: componentElement?.description || "",
      component_type: componentElement?.component_type || "",
      weight: componentElement?.weight || "",
      opacifier: componentElement?.opacifier || "",
      recyclability_status: componentElement?.recyclability_status || "",
      stage: componentElement?.stage || "",
      state: componentElement?.state || "",
      template: componentElement?.template || "",
      isEdited: componentElement?.isEdited || "",
      isDataComplete: componentElement?.isDataComplete || "",
      isCalculated: componentElement?.isCalculated || "",
      sub_components: componentElement?.sub_components?.map(
        (sub_component) => ({
          name: sub_component?.name || "",
          opacity: sub_component?.opacity || "",
          color: sub_component?.color || "",
          finishing_process: sub_component?.finishing_process || "",
          material: sub_component?.material?.map((materialElement) => ({
            material_name: materialElement?.material_name || "",
            material_type: materialElement?.material_type || "",
            layer: materialElement?.layer || "",
            converting_process: materialElement?.converting_process || "",
            material_pct: materialElement?.material_pct || "",
          })),
        })
      ),
    })),
  })),
  createdBy: auditData?.createdBy,
  modifiedBy: auditData?.modifiedBy,
});
