export interface IConstituent {
    Constituent: {
        CONNumber: string
        USINCIName: string,
        EUINCIName: string,
        commonName: string,
        JnJStatus: string,
        EINECSNumber: string,
        CASNumber: string,
        CTFAIDNumber: string,
        createdBy: string,
        scale_Ind: string,
        primaryFunction: string,
        noaelOral: string,
        prop65: string,
        constituentEnvScore: string,
        CMR_EU: string,
        INNName: string,
        IUBMBName: string,
        IUPACName: string,
        CINumber: string,
        FDnCName: string,
        DnCName: string,
        phEurName:string,
        USAN: string,
        percentage: string,
        environmentalScore:string,
        minPercentage: string,
        maxPercentage: string,
        RMINCI: string,
        intended: string,
        nanoEU: string,
        INSNumber: string,
        FMLStatus: string,
        absorptionOral: string,
        absorptionDermal: string,
        noaelDermal: string,
        RMCStatus: string,
        createdDate: string,
        usp_name: string,
        absorptionInhale: string,
        noaelInhalation: string,
        mosRegulated: string,
        mosMaxPct: string,
        mosCompromisedNr: string,
        mosCompromisedAbs: string,
        mosComments: string,
        residualSolventClassification: string,
        residualSolventMaxLimit: string,
        Synonyms: string[],
        cSubHighConc: string,
        ilAllergen: string
    }
}